// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AlgoliaSearchBox: typeof import('./.vitepress/theme/components/AlgoliaSearchBox.vue')['default']
    AppButton: typeof import('./.vitepress/theme/components/pure/AppButton.vue')['default']
    AppLayout: typeof import('./.vitepress/theme/components/AppLayout.vue')['default']
    AppLogo: typeof import('./.vitepress/theme/components/AppLogo.vue')['default']
    'Bx:bxMoon': typeof import('~icons/bx/bx-moon')['default']
    'Carbon:arrowLeft': typeof import('~icons/carbon/arrow-left')['default']
    'Carbon:logoGithub': typeof import('~icons/carbon/logo-github')['default']
    ContentLayout: typeof import('./.vitepress/theme/components/ContentLayout.vue')['default']
    DropdownLink: typeof import('./.vitepress/theme/components/DropdownLink.vue')['default']
    DropdownMenu: typeof import('./.vitepress/theme/components/DropdownMenu.vue')['default']
    'HeroiconsOutline:menuAlt2': typeof import('~icons/heroicons-outline/menu-alt2')['default']
    HomeHero: typeof import('./.vitepress/theme/components/HomeHero.vue')['default']
    IconButton: typeof import('./.vitepress/theme/components/IconButton.vue')['default']
    IonIosSunny: typeof import('~icons/ion/ios-sunny')['default']
    NavLink: typeof import('./.vitepress/theme/components/NavLink.vue')['default']
    PageFooter: typeof import('./.vitepress/theme/components/PageFooter.vue')['default']
    SidebarBackground: typeof import('./.vitepress/theme/components/SidebarBackground.vue')['default']
    SidebarHeader: typeof import('./.vitepress/theme/components/SidebarHeader.vue')['default']
    SidebarLink: typeof import('./.vitepress/theme/components/SidebarLink.vue')['default']
    SidebarLinkItem: typeof import('./.vitepress/theme/components/SidebarLinkItem.vue')['default']
    SidebarNav: typeof import('./.vitepress/theme/components/SidebarNav.vue')['default']
    TheHeader: typeof import('./.vitepress/theme/components/templates/TheHeader.vue')['default']
    TheHome: typeof import('./.vitepress/theme/components/templates/TheHome.vue')['default']
    TheLayout: typeof import('./.vitepress/theme/components/templates/TheLayout.vue')['default']
    ThePage: typeof import('./.vitepress/theme/components/templates/ThePage.vue')['default']
    TheSidebar: typeof import('./.vitepress/theme/components/templates/TheSidebar.vue')['default']
    ToggleDark: typeof import('./.vitepress/theme/components/ToggleDark.vue')['default']
    ToggleSidebar: typeof import('./.vitepress/theme/components/ToggleSidebar.vue')['default']
    TreeLink: typeof import('./.vitepress/theme/components/TreeLink.vue')['default']
    TreeMenu: typeof import('./.vitepress/theme/components/TreeMenu.vue')['default']
    'Uil:angleDown': typeof import('~icons/uil/angle-down')['default']
    'Uil:angleRight': typeof import('~icons/uil/angle-right')['default']
  }
}

export { }
